const CLIENT_ID = "YOUR_GOOGLE_CLIENT_ID";
const CLIENT_SECRET = "YOUR_GOOGLE_CLIENT_SECRET";
const REDIRECT_URI = "YOUR_GOOGLE_REDIRECT_URI";

module.exports = { CLIENT_ID, CLIENT_SECRET, REDIRECT_URI };
